#!/bin/bash
source /etc/profile
cd /waka
pacman --noconfirm -Syu
pacman --noconfirm -Sy #KERNEL# namcap
tar xzfp #TARBALL#

# run makepkg and log the output
(makepkg -s -L --noconfirm --noprogressbar 2>&1)
if [ $? -gt 0 ]; then
	(echo ">>>>>>>>>> Error building <<<<<<<<<<" 1>>makepkg.log 2>&1)
	exit 1
fi

# print the package filelist to the build log
(echo ":::::::::: Filelist ::::::::::" 1>>makepkg.log 2>&1)
(cat pkg/.FILELIST 1>>makepkg.log 2>&1)

# run namcap and add output to the build log
(echo ":::::::::: Running namcap ::::::::::" 1>>makepkg.log 2>&1)
(namcap PKGBUILD *.pkg.tar.gz 1>>makepkg.log 2>&1)
