#!/bin/bash

# include for enviromental settings
source /etc/makepkg.conf
## get configuration stuff
#source /mnt/temp/wakachroot/mkchroot.conf

CLEANUP=1

ARGLIST=$@
TARBALL=""
PKGDEST=""
LOGDEST=""
CONFIGFILE="/etc/mkchroot.conf"

while [ "$#" -ne "0" ]; do
	case $1 in
		--help)
			usage
			exit 0
			;;
		--*)
			usage
			exit 1
			;;
		-*)
			while getopts "ht:w:l:o:" opt; do
				case $opt in
					h)
						usage
						exit 0
						;;
					w)
						PKGDEST=$OPTARG
						shift
						;;
					l)
						LOGDEST=$OPTARG
						shift
						;;
					o)
						CONFIGFILE=$OPTARG
						shift
						;;
					*)
						usage
						exit 1
						;;
				esac
			done
			;;
		*)
			if [ "$TARBALL" = "" ]; then
				TARBALL=$1
			fi
			;;
	esac
	shift
done

if [ ! -f $CONFIGFILE ]; then
	msg "No config file found: $CONFIGFILE"
	usage
	exit 1
fi

# get configuration stuff
source $CONFIGFILE
# now get some function library of ours up
source /usr/share/waka/functions

if [ "$TARBALL" = "" -o ! -f "$TARBALL" ]; then
	msg "Source package not found"
	usage
	exit 1
fi

if [ "$PKGDEST" = "" ]; then
	PKGDEST=$DEFAULT_PKGDEST
fi

if [ "$LOGDEST" = "" ]; then
	LOGDEST=$DEFAULT_PKGDEST
fi


makeroot
fs_bind
(quickinst)

# mount kernel stuff to make system sane
fs_mount

# copy general configuration from host system
conf_update

if [ -f $TARBALL ]; then
	mkdir $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka
	cp $TARBALL $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/ || error "Source tarball not found!"

	cp /usr/share/waka/build $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/build
	JUSTTARBALL=`basename $TARBALL`
	sed -i "s|#TARBALL#|${JUSTTARBALL}|g"       $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/build
	sed -i "s|#KERNEL#|${DEFAULT_KERNEL}|g" $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/build
	
	chmod +x $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/build
	msg "Starting to build package..."
	chroot $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/ /waka/build
	source $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/PKGBUILD

	mv $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/$pkgname-$pkgver-$pkgrel.pkg.tar.gz $PKGDEST || warning "Package could not be retrieved!"
	mv $WAKA_ROOT_DIR/$WAKA_CHROOT_DIR/waka/makepkg.log $LOGDEST/$pkgname-$pkgver-$pkgrel.makepkg.log || warning "Logfile could not be retrieved!"
else
	error "Could not find source tarball!"
	exit 2
fi

fs_unbind
fs_umount

if [ ${CLEANUP} -eq 1 ]; then
	cleanup
fi
