#!/bin/bash

myver="0.4"

# include for enviromental settings
source /etc/makepkg.conf

# default values
TARBALL=""
PKGDEST=""
LOGDEST=""
CONFIGFILE="/etc/mkchroot.conf"
PACMANFILE=""
CREATEIMG=""
USEIMG=""

# message functions
# TODO these are the same as makepkg functions, so make them
# common in /usr/share/archlinux

plain() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "    \033[1;1m$1\033[1;0m" >&2
	else
		echo "    $1" >&2
	fi
}

msg() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;32m==>\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> $1" >&2
	fi
}

warning() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;33m==> WARNING:\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> WARNING: $1" >&2
	fi
}

error() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;31m==> ERROR:\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> ERROR: $1" >&2
	fi
	exit 2
}

# wakachroot functions

# clean up any files left in the chroot path
cleanup() {
	if [ -d $rootpath ]; then
		msg "Removing old virtual root... (This may take a while)"
		rm -rf $rootpath
	fi
}

# make a new chroot directory at the specified path
makeroot() {
	local ret=0
	cleanup
	mkdir $rootpath || ret=1

	return $ret
}

# mount sysfs and proc filesystems, and copy devfs
fs_mount() {
	local ret=0
	msg "Mounting sysfs..."
	mount -t sysfs  sysfs  $rootpath/sys || ret=1
	msg "Mounting procfs..."
	mount -t proc   proc   $rootpath/proc || ret=1
#	mount -t usbfs  usbfs  $rootpath/proc/bus/usb || ret=1
	msg "Copying devfs..."
	cp -a /dev $rootpath/dev || ret=1

	return $ret
}

# unmount sysfs and proc filesystems (doing nothing with copied devfs)
fs_umount() {
	local ret=0
	msg "Umounting sysfs..."
	umount $rootpath/sys || ret=1
	msg "Umounting procfs..."
#	umount $rootpath/proc/bus/usb || ret=1
	umount $rootpath/proc || ret=1

	return $ret
}

# bind the 'global package cache' inside of the chroot (to save on downloading)
fs_bind() {
	local ret=0
	msg "Using global package cache..."
	mkdir -p $rootpath/var/cache/pacman/pkg || ret=1

	# Try hard linking- if that doesn't work, try copying
	cp -l /var/cache/pacman/pkg/* $rootpath/var/cache/pacman/pkg/ || cp /var/cache/pacman/pkg/* $rootpath/var/cache/pacman/pkg/ || ret=1

	return $ret
}

# unbind the 'global package cache', copying any new downloads back
fs_unbind() {
	rsync -a $rootpath/var/cache/pacman/pkg/* /var/cache/pacman/pkg/
	rm $rootpath/var/cache/pacman/pkg/*
}

# call the quickinst script to install packages from FTP
quickinst() {
	if [ -f /tmp/packages.txt ]; then
		rm /tmp/packages.txt
	fi
	msg "Running $QUIKINST_LOCATION ftp $rootpath $PACKAGE_MIRROR_CURRENT"
	source $QUIKINST_LOCATION ftp $rootpath $PACKAGE_MIRROR_CURRENT || return 1
}

# copy resolv.conf from host system and create a pacman.conf file
conf_update() {
	cp -L /etc/resolv.conf $rootpath/etc || return 1

	if [ "$PACMANFILE" = "" ]; then
		echo "[current]" > $rootpath/etc/pacman.d/current
		echo "Server = ${PACKAGE_MIRROR_CURRENT}" >> $rootpath/etc/pacman.d/current

		echo "[extra]" > $rootpath/etc/pacman.d/extra
		echo "Server = ${PACKAGE_MIRROR_EXTRA}" >> $rootpath/etc/pacman.d/extra
	else
		cp $PACMANFILE $rootpath/etc/pacman.conf || return 1
	fi
}

# usage function
usage() {
	echo "mkchroot version $myver"
	echo "usage: $0 [options] <source package>"
	echo "options:"
	echo "  -h, --help        This help"
	echo "  -w <destdir>      Write package to <destdir> instead of the working dir"
	echo "  -l <destdir>      Write build log to <destdir> instead of the working dir"
	echo "  -o <configfile>   Use an alternate config file"
	echo "  -p <pacmanconfig> Use an alternate pacman config file"
	echo "  -c <imgfile>      Create an image to use in subsequent builds"
	echo "  -i <imgfile>      Use image as build base"
}

# PROGRAM START

# parse command line arguments
while [ $# -ne 0 ]; do
	case $1 in
		--help)
			usage
			exit 0
			;;
		--*)
			usage
			exit 1
			;;
		-*)
			OPTIND=0
			while getopts "hw:l:p:o:c:i:" opt; do
				case $opt in
					h)
						usage
						exit 0
						;;
					w)
						PKGDEST=$OPTARG
						shift
						;;
					l)
						LOGDEST=$OPTARG
						shift
						;;
					p)
						PACMANFILE=$OPTARG
						shift
						;;
					o)
						CONFIGFILE=$OPTARG
						shift
						;;
					c)
						CREATEIMG=$OPTARG
						shift
						;;
					i)
						USEIMG=$OPTARG
						shift
						;;
					*)
						usage
						exit 1
						;;
				esac
			done
			;;
		*)
			if [ "$TARBALL" = "" ]; then
				TARBALL=$1
			fi
			;;
	esac
	shift
done

# check if config file is a valid file path
if [ ! -f $CONFIGFILE ]; then
	msg "No config file found: $CONFIGFILE"
	usage
	exit 1
fi

# get configuration (done here so it can be specified on command line)
source $CONFIGFILE

# now that we've sourced the config file - let's make referencing
# the most commmon path nice and easy
rootpath="$WAKA_ROOT_DIR/$WAKA_CHROOT_DIR"

# resolve output paths to absolute paths
if [ "$CREATEIMG" != "" ]; then
	if echo $CREATEIMG | grep -v ^/ 2>&1 > /dev/null; then
		CREATEIMG="$(pwd)/$CREATEIMG"
	fi
fi
if [ "$TARBALL" != "" ]; then
	if echo $TARBALL | grep -v ^/ 2>&1 > /dev/null; then
		TARBALL="$(pwd)/$TARBALL"
	fi
fi

# if we aren't creating a tarball or an image, we have a problem
if [ \( "$TARBALL" = "" -o ! -f "$TARBALL" \) -a "$CREATEIMG" = "" ]; then
	msg "Source package not found"
	usage
	exit 1
fi

# if PKGDEST or LOGDEST are undefined, set them to their defaults
if [ "$PKGDEST" = "" ]; then
	PKGDEST=$DEFAULT_PKGDEST
fi
if [ "$LOGDEST" = "" ]; then
	LOGDEST=$DEFAULT_PKGDEST
fi

# set up the chroot directory
makeroot
if [ $? -ne 0 ]; then
	error "Can't create chroot directory"
fi

# if we aren't using a preexisting image, do an install
if [ -z "$USEIMG" ]; then
	msg "Installing base chroot image..."
	fs_bind # we ignore a failure of fs_bind, use && if we shouldn't
	quickinst
	if [ $? -ne 0 ]; then
		fs_unbind
		error "Can't build chroot"
		#exit 1 # TODO failure course of action
	fi
else
	msg "Extracting base image..."
	cd $rootpath
	tar -xjf $USEIMG
	if [ $? -ne 0 ]; then
		error "Can't extract image"
		#exit 1 # TODO failure course of action
	fi
	# TODO why wasn't this here before?
	#fs_bind # if fs_bind fails, we will just end up always downloading
fi

# if CREATEIMG is defined, zip up the image to the specified location
# and exit the script- we don't need to build a package
if [ -n "$CREATEIMG" ]; then
	msg "Creating base image..."
	fs_unbind
	cd $rootpath
	tar -cjf $CREATEIMG *
	if [ $? -ne 0 ]; then
		cleanup
		error "Can't create image"
		exit 1
	fi
	cleanup
	exit 0
fi

# mount kernel stuff to make system sane
fs_mount
if [ $? -ne 0 ]; then
	fs_umount
	fs_unbind
	cleanup
	error "Problem mounting filesystems"
	#exit 1 # TODO failure course of action
fi

# copy general configuration from host system
conf_update
if [ $? -ne 0 ]; then
	fs_umount
	fs_unbind
	cleanup
	error "Problem updating configs"
	#exit 1 # TODO failure course of action
fi

if [ -f $TARBALL ]; then
	# make a /waka directory and populate it with necessary files
	mkdir $rootpath/waka
	cp $TARBALL $rootpath/waka/

	cp /usr/share/waka/build $rootpath/waka/build
	JUSTTARBALL=$(basename $TARBALL)
	# wow, this is a bit hacky
	sed -i "s|#TARBALL#|${JUSTTARBALL}|g" $rootpath/waka/build
	sed -i "s|#KERNEL#|${DEFAULT_KERNEL}|g" $rootpath/waka/build
	
	chmod +x $rootpath/waka/build
	msg "Starting to build package..."
	# chroot and kick off the build...
	chroot $rootpath/ /waka/build
	# ...and we're back. source the PKGBUILD for fetching the package
	source $rootpath/waka/PKGBUILD

	# TODO this is going to fail hard with pacman3, there should be a better way
	mv $rootpath/waka/$pkgname-$pkgver-$pkgrel.pkg.tar.gz $PKGDEST || warning "Package could not be retrieved!"
	mv $rootpath/waka/makepkg.log $LOGDEST/$pkgname-$pkgver-$pkgrel.makepkg.log || warning "Logfile could not be retrieved!"
else
	error "Could not find source tarball!"
fi

fs_unbind
fs_umount
cleanup

