#!/bin/sh
# $Id: quickinst,v 1.19 2007/10/05 13:17:16 tpowa Exp $

usage() {
	echo "quickinst <install_mode> <destdir> <package_directory|server_url>"
	echo
	echo "This script is for users who would rather partition/mkfs/mount their target"
	echo "media manually than go through the routines in the setup script."
	echo
	echo "First make sure you have all your filesystems mounted under <destdir>."
	echo "e.g. mount -t iso9660 /dev/sdc or /dev/sr0 (for new naming sheme) /src "
	echo "Then run this script to install all base packages to <destdir>."
	echo
	if [ -e /usr/bin/wget ]; then
		echo "<install_mode> must be either 'ftp' or 'cd'"
	else
		echo "<install_mode> must be 'cd'"
	fi
	echo
	echo "Examples:"
	if [ -e /usr/bin/wget ]; then
		if [ "$(uname -m)" = "x86_64" ]; then
    			echo "  quickinst ftp /mnt ftp://ftp.archlinux.org/core/os/x86_64"
		else 	
			echo "  quickinst ftp /mnt ftp://ftp.archlinux.org/core/os/i686"
		fi
	fi

	echo "  quickinst cd  /mnt /src/core/pkg"
	echo ""
	exit 0
}

INSTMODE=$1
DESTDIR=$2
PKGARG=$3

if [ "$PKGARG" = "" ]; then
	usage
fi

! [ -d /tmp ] && mkdir /tmp

# sometimes this gets mounted RO, dunno why
/bin/mount -o remount,rw /

PACMAN=
[ -f /tmp/usr/bin/pacman.static ] && PACMAN=/tmp/usr/bin/pacman.static
[ -f /usr/bin/pacman.static ] && PACMAN=/usr/bin/pacman.static
if [ "$PACMAN" = "" ]; then
	cd /tmp
	if [ "$INSTMODE" = "ftp" ]; then
		echo "Downloading pacman..."
		wget $PKGARG/pacman*.pkg.tar.gz
		if [ $? -gt 0 ]; then
			echo "error: Download failed"
			exit 1
		fi
		tar -xzf pacman*.pkg.tar.gz
	elif [ "$INSTMODE" = "cd" ]; then
		echo "Unpacking pacman..."
		tar -xzf $PKGARG/pacman*.pkg.tar.gz
	fi
fi
[ -f /tmp/usr/bin/pacman.static ] && PACMAN=/tmp/usr/bin/pacman.static
if [ "$PACMAN" = "" ]; then
	echo "error: Cannot find the pacman.static binary!"
	exit 1
fi

if [ "$INSTMODE" = "ftp" ]; then
	PKGFILE=/tmp/packages.txt
	cd /tmp
	wget $PKGARG/packages.txt
	if [ $? -gt 0 ]; then
		echo "error: Could not fetch package list from server"
		exit 1
	fi
	echo "[core]" >/tmp/pacman.conf
	echo "Server = $PKGARG" >>/tmp/pacman.conf
fi

if [ "$INSTMODE" = "cd" ]; then
	PKGFILE=/tmp/packages.txt
	cp $PKGARG/packages.txt /tmp/packages.txt
	if [ ! -f $PKGFILE ]; then
		echo "error: Could not find package list: $PKGFILE"
		exit 1
	fi
	echo "[core]" >/tmp/pacman.conf
	echo "Server = file://$PKGARG" >>/tmp/pacman.conf
fi

PKGLIST=
# fix pacman list!
sed -i -e 's/-i686//g' -e 's/-x86_64//g' $PKGFILE
for i in $(cat $PKGFILE | grep 'base/' | cut -d/ -f2); do
	nm=${i%-*-*}
	PKGLIST="$PKGLIST $nm"
done
mkdir -p $DESTDIR/var/cache/pacman
# mount proc/sysfs first, so mkinitrd can use auto-detection if it wants
! [ -d $DESTDIR/proc ] && mkdir $DESTDIR/proc
! [ -d $DESTDIR/sys ] && mkdir $DESTDIR/sys
! [ -d $DESTDIR/dev ] && mkdir $DESTDIR/dev
mount -t proc none $DESTDIR/proc
mount -t sysfs none $DESTDIR/sys
mount -o bind /dev $DESTDIR/dev	
$PACMAN -r $DESTDIR --config /tmp/pacman.conf -Sy $PKGLIST
umount $DESTDIR/proc $DESTDIR/sys $DESTDIR/dev
if [ $? -gt 0 ]; then
	echo
	echo "Package installation FAILED."
	echo
	exit 1
fi
